### ISSUE TITLE
Code not working with the supplied jar

### ISSUE THREAD

**Issue by manuag11** [mikelewis0/EasySRL#39]
I get the following error when I try to run the project using the existing jar. Also, if I try to compile the code using ant, it shows up a lot of errors and the project does not build properly. Any clues on this would be greatly appreciated. Thanks.
$ /opt/bb/bin/java8 -jar ../easysrl.jar --model ../model
====Starting loading model====
Reading POS tagger model from ../model/pipeline/posTagger ... done [0.5 sec].
Exception in thread "main" java.lang.UnsatisfiedLinkError: /tmp/deeptaggerlibdeeptagger.so: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /tmp/deeptaggerlibdeeptagger.so)
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
        at java.lang.Runtime.load0(Runtime.java:809)
        at java.lang.System.load(System.java:1086)
        at edu.uw.deeptagger.DeepTagger.loadLib(DeepTagger.java:57)
        at edu.uw.deeptagger.DeepTagger.loadFromJar(DeepTagger.java:35)
        at edu.uw.deeptagger.DeepTagger.<clinit>(DeepTagger.java:25)
        at edu.uw.easysrl.syntax.tagger.TaggerLSTM.makeDeepTagger(Unknown Source)
        at edu.uw.easysrl.syntax.tagger.TaggerLSTM.<init>(Unknown Source)
        at edu.uw.easysrl.syntax.tagger.Tagger.make(Unknown Source)
        at edu.uw.easysrl.main.EasySRL.makeParser(Unknown Source)
        at edu.uw.easysrl.main.EasySRL.makeParser(Unknown Source)
        at edu.uw.easysrl.main.EasySRL.makeParser(Unknown Source)
        at edu.uw.easysrl.main.EasySRL.makePipelineParser(Unknown Source)
        at edu.uw.easysrl.main.EasySRL.main(Unknown Source)

**Comment by aminorex** [comment]
Same issue
